// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getApiKey: () => typedError<string, string>(__TAURI_INVOKE("get_api_key")),
	setApiKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("set_api_key", { key })),
	getGlobalSchedule: () => typedError<string, string>(__TAURI_INVOKE("get_global_schedule")),
	setGlobalSchedule: (time: string) => typedError<null, string>(__TAURI_INVOKE("set_global_schedule", { time })),
	getSchedulerAutoRun: () => typedError<boolean, string>(__TAURI_INVOKE("get_scheduler_auto_run")),
	setSchedulerAutoRun: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_scheduler_auto_run", { enabled })),
	getLaunchAtStartup: () => typedError<boolean, string>(__TAURI_INVOKE("get_launch_at_startup")),
	setLaunchAtStartup: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_launch_at_startup", { enabled })),
	fetchProjectsPage: (page: number) => typedError<PaginatedResponse<FreispaceProject>, string>(__TAURI_INVOKE("fetch_projects_page", { page })),
	fetchStoragesPage: (page: number) => typedError<PaginatedResponse<FreispaceStorage>, string>(__TAURI_INVOKE("fetch_storages_page", { page })),
	fetchStorageProjectsPage: (page: number) => typedError<PaginatedResponse<StorageProjectItem>, string>(__TAURI_INVOKE("fetch_storage_projects_page", { page })),
	syncEntityNames: () => typedError<null, string>(__TAURI_INVOKE("sync_entity_names")),
	syncEntityNamesFull: () => typedError<null, string>(__TAURI_INVOKE("sync_entity_names_full")),
	getEntityNames: () => typedError<CachedEntityName[], string>(__TAURI_INVOKE("get_entity_names")),
	listFolderConfigs: () => typedError<FolderConfig[], string>(__TAURI_INVOKE("list_folder_configs")),
	upsertFolderConfig: (input: FolderConfigInput) => typedError<FolderConfig, string>(__TAURI_INVOKE("upsert_folder_config", { input })),
	deleteFolderConfig: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_folder_config", { id })),
	pickFolder: () => typedError<string | null, string>(__TAURI_INVOKE("pick_folder")),
	listStorageProjectSettings: () => typedError<StorageProjectSetting[], string>(__TAURI_INVOKE("list_storage_project_settings")),
	setStorageProjectEnabled: (storageId: string, projectId: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_storage_project_enabled", { storageId, projectId, enabled })),
	removeStorageProject: (storageId: string, projectId: string) => typedError<null, string>(__TAURI_INVOKE("remove_storage_project", { storageId, projectId })),
	triggerAll: () => typedError<null, string>(__TAURI_INVOKE("trigger_all")),
	triggerStorageProject: (storageId: string, projectId: string) => typedError<null, string>(__TAURI_INVOKE("trigger_storage_project", { storageId, projectId })),
	listLogEntries: (levelFilter: string | null, limit: number, offset: number) => typedError<LogEntry[], string>(__TAURI_INVOKE("list_log_entries", { levelFilter, limit, offset })),
	clearLogEntries: () => typedError<null, string>(__TAURI_INVOKE("clear_log_entries")),
	saveLogFile: (content: string, defaultName: string) => typedError<boolean, string>(__TAURI_INVOKE("save_log_file", { content, defaultName })),
	showLogsWindow: () => typedError<null, string>(__TAURI_INVOKE("show_logs_window")),
};

/** Events */
export const events = {
	logEntryEvent: makeEvent<LogEntryEvent>("log-entry-event"),
	schedulerTickEvent: makeEvent<SchedulerTickEvent>("scheduler-tick-event"),
};

/* Types */
/**  A cached storage or project name fetched from the freispace API. */
export type CachedEntityName = {
	entity_type: string,
	entity_id: string,
	name: string | null,
	parent_id: string | null,
	project_number: string | null,
	color: string | null,
};

/**  A configured folder path for a storage-project pair. */
export type FolderConfig = {
	id: string,
	storage_id: string,
	project_id: string,
	folder_path: string,
	/**  HH:MM local time override, or None to use the global schedule. */
	custom_schedule: string | null,
	created_at: string,
	updated_at: string,
};

/**  Input DTO for creating or updating a folder config. */
export type FolderConfigInput = {
	storage_id: string,
	project_id: string,
	folder_path: string,
	/**  HH:MM or None to inherit the global schedule. */
	custom_schedule: string | null,
};

export type FreispaceProject = {
	id: string,
	name: string | null,
	parent_id: string | null,
	number: string | null,
	color: string | null,
};

export type FreispaceStorage = {
	id: string,
	name: string | null,
	is_active: boolean | null,
};

/**  A single log entry. */
export type LogEntry = {
	id: string,
	level: string,
	message: string,
	context: string | null,
	created_at: string,
};

/**  Emitted after every log entry is inserted. */
export type LogEntryEvent = LogEntry;

/**  Generic paginated response wrapper. */
export type PaginatedResponse<T> = {
	data: T[],
	pagination_links: PaginationLinks | null,
	pagination_meta: PaginationMeta | null,
};

/**  Pagination links returned by all freispace list endpoints. */
export type PaginationLinks = {
	first: string | null,
	last: string | null,
	prev: string | null,
	next: string | null,
};

/**  Pagination meta returned by all freispace list endpoints. */
export type PaginationMeta = {
	current_page: number,
	from: number | null,
	per_page: number,
	to: number | null,
};

/**  Emitted after each storage-project is processed in a scheduler tick. */
export type SchedulerTickEvent = {
	storage_id: string,
	project_id: string,
	/**  "ok" | "warning" | "error" */
	status: string,
};

export type StorageProjectItem = {
	id: string,
	storage_id: string | null,
	project_id: string | null,
	storage_size_estimated: number | null,
	storage_size_current: number | null,
};

/**  Enabled/disabled state for a storage-project pair. */
export type StorageProjectSetting = {
	storage_id: string,
	project_id: string,
	enabled: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

